### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Tom-E-Durham** [xtreme1-io/xtreme1#170]
Hi, 

I'm trying to run the Basic Lidar object detection model on point cloud. I met the problem of: Model Run Error.

And here is output in terminal:
```
xtreme1-v073-point-cloud-object-detection-1  | 2023-11-27 10:20:23 INFO process_data: ---------- http://minio:9000/xtreme1/1/1/42147ed0df644f16a646f1c156422413/xtreme1-lidar-fusion-trial/point_cloud/binary-00.pcd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20231127%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231127T102023Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6aea353621541d42a53f1b5fc4afd5658918026b10400c90a9747e6e6709a1b7 ----------
xtreme1-v073-nginx-1                         | 172.18.0.1 - - [27/Nov/2023:10:20:23 +0000] "GET /api/data/modelAnnotationResult?dataIds=7&serialNo=1729082733822504960 HTTP/1.1" 200 87 "http://localhost:8190/tool/pc?recordId=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
xtreme1-v073-point-cloud-object-detection-1  | 2023-11-27 10:20:23 INFO log_interval: DOWNLOAD pcd(2.6MB):      0.023s
xtreme1-v073-point-cloud-object-detection-1  | 2023-11-27 10:20:23 INFO log_interval: LOAD pcd:                 0.0033s
xtreme1-v073-point-cloud-object-detection-1  | 2023-11-27 10:20:23 INFO log_interval: VALIDATE points:          0.022s
xtreme1-v073-point-cloud-object-detection-1  | 2023-11-27 10:20:23 ERROR process_data: CUDA error: no kernel image is available for execution on the device
xtreme1-v073-point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
xtreme1-v073-point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
xtreme1-v073-point-cloud-object-detection-1  | Traceback (most recent call last):
xtreme1-v073-point-cloud-object-detection-1  |   File "app.py", line 80, in process_data
xtreme1-v073-point-cloud-object-detection-1  |     results, _ = self.predictor(points=pc, full_nms=True)
xtreme1-v073-point-cloud-object-detection-1  |   File "/app/pcdet_open/src/predictor.py", line 80, in __call__
xtreme1-v073-point-cloud-object-detection-1  |     pred_dicts, _ = self.model.forward(data_dict)
xtreme1-v073-point-cloud-object-detection-1  |   File "/src/pcdet/models/detectors/centerpoint.py", line 11, in forward
xtreme1-v073-point-cloud-object-detection-1  |     batch_dict = cur_module(batch_dict)
xtreme1-v073-point-cloud-object-detection-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
xtreme1-v073-point-cloud-object-detection-1  |     return forward_call(*input, **kwargs)
xtreme1-v073-point-cloud-object-detection-1  |   File "/src/pcdet/models/backbones_3d/vfe/mean_vfe.py", line 26, in forward
xtreme1-v073-point-cloud-object-detection-1  |     points_mean = voxel_features[:, :, :].sum(dim=1, keepdim=False)
xtreme1-v073-point-cloud-object-detection-1  | RuntimeError: CUDA error: no kernel image is available for execution on the device
xtreme1-v073-point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
xtreme1-v073-point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
xtreme1-v073-point-cloud-object-detection-1  | 2023-11-27 10:20:23 INFO log_request: 200 POST /pointCloud/recognition (172.18.0.8) 307.06ms

``` 

I have installed the nvidia driver and the container driver and I am using NVIDIA RTX 3080 and Ubuntu 20.04. Are there any requirements about these for using this model?

Thanks for your help!

**Comment by jaggerwang** [comment]
Right now the CUDA version using by point cloud object detection model is `10.2`, which not support RTX 3080, you can try to update the CUDA and PyTorch version in the [Dockerfile](https://github.com/xtreme1-io/point-cloud-object-detection) to 11+, and build your own image. For more information, you can reference this article https://forums.developer.nvidia.com/t/can-rtx-3080-support-cuda-10-1/155849.

**Comment by Tom-E-Durham** [comment]
Thanks for your quick answer, jaggerwang. I have rebuilt the pointcloud object detection image as you said. It works! Thanks a lot.

**Comment by jaggerwang** [comment]
You are welcome:)

**Comment by Creating-ZXY** [comment]
> Right now the CUDA version using by point cloud object detection model is `10.2`, which not support RTX 3080, you can try to update the CUDA and PyTorch version in the [Dockerfile](https://github.com/xtreme1-io/point-cloud-object-detection) to 11+, and build your own image. For more information, you can reference this article https://forums.developer.nvidia.com/t/can-rtx-3080-support-cuda-10-1/155849.

Could you please share how to compile this?
